[v1]
"bacon 3.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"cargo-binstall 1.10.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
"cargo-info 0.7.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-info"]
"cargo-readme 3.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-readme"]
"du-dust 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"gitui 0.26.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitui"]
"irust 1.71.27 (registry+https://github.com/rust-lang/crates.io-index)" = ["irust"]
"kanata 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["kanata"]
"mprocs 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["mprocs"]
"ripgrep 14.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sccache 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["sccache"]
"starship 1.21.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"zellij 0.40.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
"cargo-msrv 0.16.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-msrv"]
